language: python
python:
  - 3.6
  - 3.7
  - "nightly"

matrix:
  allow_failures:
    - python: "nightly"

sudo: false

install:
  - pip install -r requirements.txt

script:
  - coverage run -m unittest discover

after_success:
  - codecov